### ISSUE TITLE
Converting margin or padding with 4 values gives you wrong value

### ISSUE THREAD

**Issue by sagachoo** [hunghg255/css2tailwind#11]
For example, converting a css from
margin: 10px 20px 30px 20px 
or 
padding: 10px 20px 30px 20px 

generated this
ml-[20px] mr-[20px] my-[10px]
or
pl-[20px] pr-[20px] py-[10px]

The 30px for bottom side is lost. The expected result should be
ml-[20px] mr-[20px] mt-[10px] mb-[30px]
or
pl-[20px] pr-[20px] pt-[10px] pb-[30px]

Overall, this extension is very good. Please fix the issue.

**Comment by hunghg255** [comment]
I fixed this! thank for your report

**Comment by sagachoo** [comment]
Thanks for fixing this but the generated value a bit wrong
e.g.
padding: 40px 12px 12px 12px; 
generates 
pt_[40px] px_[12px] pb_[12px]

The values should be hyphen instead of underscore.
pt-[40px] px-[12px] pb-[12px]

Thank you

**Comment by hunghg255** [comment]
> padding: 40px 12px 12px 12px;

I fixed this thanks

**Comment by sagachoo** [comment]
Thanks for fixing that but still not quite right for margin
For example, converting

margin: 10px 20px 30px 40px;

got this

-mt[10px] -mr[20px] -mb[30px] -ml[40px]

The hyphens are in the wrong place, should be
mt-[10px] -mr-[20px] -mb-[30px] -ml-[40px]

**Comment by hunghg255** [comment]
> Thanks for fixing that but still not quite right for margin For example, converting
> 
> margin: 10px 20px 30px 40px;
> 
> got this
> 
> -mt[10px] -mr[20px] -mb[30px] -ml[40px]
> 
> The hyphens are in the wrong place, should be mt-[10px] -mr-[20px] -mb-[30px] -ml-[40px]

I fixed this
